### ISSUE TITLE
Hats Glitch

### ISSUE THREAD

**Issue by FluxcapGaming** [iChun/Hats#128]
I am playing Sky Factory 1 and one of my hats has been broken pretty much from day 1.  The hat in question is the Stone Mask.  It spawned fine at first but the graphics became invisible.  I tried trading it to a friend to see if that would fix it.  When I did the name stayed on my list of hats but still was broken.  I have tried reinstalling the game completely, and even reformatting my computer.  Is there a way to reload the hats and a command to give the hats back I currently have?  Thank you

**Comment by iChun** [comment]
Can you show me a screenshot?

**Comment by FluxcapGaming** [comment]
Certainly...  Please excuse my Herobrine skin.  This is not a joke, it is just the skin I use...

As you can see in the first picture I have the Stone Mask selected but it does not appear...

Also, I looked through the files and found the Stone Make tcn file and noticed it is the only one with an extra space before the ".tcn"... not sure if it this is helps, however, removing the space does not correct the issue.

Thanks for your reply so quickly.


![stone mask](https://cloud.githubusercontent.com/assets/8891081/5693763/72196508-98fb-11e4-854e-2fd7cbcec1ce.png)

![extra space](https://cloud.githubusercontent.com/assets/8891081/5693764/760907d6-98fb-11e4-8ad5-ddf57763abfe.png)

**Comment by FluxcapGaming** [comment]
I am just curious, but have you looked into this at all?  I know it isn't a major major bug, and probably just a fluke.  But I would love to get this fixed as it is bothering me.  Thanks again

**Comment by iChun** [comment]
I have not, recently. I've been busy as of late.

**Comment by iChun** [comment]
Does anything print into the console when you use the hat?

**Comment by FluxcapGaming** [comment]
Is there another console beside the chat console?  I don't see anything print in chat when I equipt the hat.

**Comment by iChun** [comment]
Not chat, like, java console.

**Comment by FluxcapGaming** [comment]
Ah, lol, sorry, I thought you meant an in game console.

Nothing at all prints when I change to any hat.

**Comment by iChun** [comment]
When you put the specific stone hat on?

**Comment by FluxcapGaming** [comment]
I put the hat on, the first day I played.  I was able to wear it just fine.  When I switched between several hats to try them on the stone mask glitched and became invisible.  I attempted to trade it to another player.  They had the hat in their hat list but was also available and it stayed on my list.  They traded it back to me and then I had two stone masks in my item list.  I traded it back to him and only had one left on my list.  It was glitched ever sence.

**Comment by iChun** [comment]
I meant, does anything pop up in the console when you try to wear the stone
mask

**Comment by FluxcapGaming** [comment]
Nothing pops up at all in the console. Not even with working hats

**Comment by iChun** [comment]
Have you tried deleting the hats file to purge a redownload of the file?

**Comment by FluxcapGaming** [comment]
Yes, this does not work.

**Comment by iChun** [comment]
Well I'm not sure how I can help with this really as the Techne importer
has had some changes with as of late to adapt it to favour my Tabula
format.

The most I can help is to look into this in the future when the hats are
being converted to the Tabula format for 1.8

**Comment by FluxcapGaming** [comment]
Is there a command to add/remove hats?  Like if I remove the stone mask then add it back

**Comment by iChun** [comment]
No, the server would have a store of it unfortunately.

**Comment by FluxcapGaming** [comment]
I am not on a server.  I am on my machine.

**Comment by iChun** [comment]
You play multiplayer on LAN?

**Comment by FluxcapGaming** [comment]
I normally just play singleplayer, but I let my friend join via open to lan.

**Comment by iChun** [comment]
I don't think there's anything I can really do about it at this stage
except to request you ignore the one hat out of the many hats included in
the mod right now. I'll keep it in mind for the port for 1.8 however.

**Comment by FluxcapGaming** [comment]
I found out that if I delete hats.dat file it clears all my hats, including the glitched one.  I can send you my glitched hats.dat if that helps you in any way.  Deleting this file should have no other changes to the game, correct?

**Comment by iChun** [comment]
You have to go unlock all of them again though.

**Comment by FluxcapGaming** [comment]
I deleted it and found that I was able to edit it to give me back my hats, but when I type "Stone Mask" it still is glitched...  I also noticed my friend's hat list had "Stone Mask" without a space after it like I did...

**Comment by iChun** [comment]
Like I said before, There really isn't much I can do about this

**Comment by iChun** [comment]
Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.

**Comment by Ninj4X0rignlal** [comment]
I don't know what to say
![image](https://user-images.githubusercontent.com/75673777/117539383-a9364600-b00a-11eb-9e77-6f3eb4e326c8.png)
