### ISSUE TITLE
hats not showing on mobs in mp

### ISSUE THREAD

**Issue by ryan2109** [iChun/Hats#130]
The hat mod works great on single player but as soon as I try and use it on my server everything works except there are no hats on any mobs at all, I do have it set on option 4 and have it at 100%

abd none of the mobs in the worlds have hats on either

**Comment by iChun** [comment]
Can you post the log for your server?

**Comment by iChun** [comment]
Also make sure that the mod was installed from the start. Only new mobs spawning will get hats. Pre existing mobs won't be getting hats (I think)

**Comment by ryan2109** [comment]
i no longer have logs as i ended up changing too new server (due too host issues) and upon changing the mod worked fine
