### ISSUE TITLE
FTP Error 550 (Can't delete hats/Contributors via FileZilla)

### ISSUE THREAD

**Issue by 61352151511** [iChun/Hats#131]
No matter how many times I try the hats/Contributors folder can't be deleted from my server via FileZilla. Not sure if it's how the folder is generated from the mod, if not probably not on your end.

**Comment by iChun** [comment]
File.mkdirs();

**Comment by 61352151511** [comment]
That's weird, I'll test it again later, it might just be the host, no idea.

**Comment by iChun** [comment]
Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.
