### ISSUE TITLE
High Client worldTick() time.

### ISSUE THREAD

**Issue by iChun** [iChun/Hats#132]
https://www.dropbox.com/s/anyukzkonv91ils/Screenshot%202015-03-15%2004.03.52.png?dl=0

**Comment by Fundaris** [comment]
https://github.com/iChun/Hats/blob/master/src/main/java/hats/client/core/TickHandlerClient.java

Line 248: contains eats much time after serveral minutes

clearing requestedMobHats after some time/amount/(moved away) should fix it. 

How expensive is it to request a mob hat again in that scenario.
