### ISSUE TITLE
Hat stand protection

### ISSUE THREAD

**Issue by prodkid** [iChun/Hats#133]
Would it be possible to define protection on hat stands for server/admins/players so other players can't change or unequip hats? Currently, anyone can place down a hat stand and an another player could modify the hat stand. I am creating an in-game hat store and want to showcase these hats but players could modify the stands.

**Comment by iChun** [comment]
Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.
