### ISSUE TITLE
[Suggestion] Hat unlock announcement

### ISSUE THREAD

**Issue by 61352151511** [iChun/Hats#135]
Servers could have a config for the rarity level of announcements. So say this value is set to 7 (I believe the most rare), whenever someone gets the rarest hat it is announced in chat like achievements are. If it's set to 5 and someone gets a hat with rarity level 5, 6, or 7, it will announce it.

**Comment by iChun** [comment]
Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.
