### ISSUE TITLE
Crash with server

### ISSUE THREAD

**Issue by uhsting** [iChun/Hats#146]
Hi! There is a crash with the server when I am just flying and wandering around the map and maybe when I look at a mob with a hat or a mob with a hat spawned, Minecraft crashed. Here is the error log:

http://pastebin.com/auPBhSd1

Would be more than welcome if there is a solution to this!

**Comment by DPxKnightxZero** [comment]
What does that crash have to do with this mod? Its says its caused by mystcraft ...
