### ISSUE TITLE
Crash related to recurrent complex structures

### ISSUE THREAD

**Issue by starg09** [iChun/Hats#152]
Hi, I know you mentioned you're dropping support for this mod, but I was hoping maybe this was something you would consider fixing eventually. This happens in the latest version of Hats for 1.7.10, with [Recurrent Complex](http://minecraft.curseforge.com/mc-mods/223150-recurrent-complex) installed. [I made an issue on their side first](http://github.com/Ivorforce/RecurrentComplex/issues/30), but they mentioned "there's nothing they can do on their end."

Basically, as Ivorius mentions on the linked report, there's a check made by Hats about spawners nearby when the tile entity hasn't been initialized properly yet (this may not be written correctly, I insist in checking the original comment to get it right).

Is there any chance you could check on this, and see if it can be fixed? It's quite a random crash, but it can break a world permanently if the user has not enough knowledge for removing the correct mod, then enabling it again :/

**Comment by iChun** [comment]
Sorry, I know it's been 4 years, but that version of the mod has long stopped receiving support, yeah. 

If it makes you feel better though, Hats causing crashes with Mob Spawners was eventually fixed in later versions.
