### ISSUE TITLE
[Enhancement] Ability to add and remove hats from pets and farm animals

### ISSUE THREAD

**Issue by mikeloeven** [iChun/Hats#154]
So There are two issues you can encounter with the hats mod and that is Pets suddenly getting stupid looking hats you want to remove or you collecting a really awesome hat you want to put on your pet. Currently with the completely randomized hat system players have no control over the hats that their pets and farm animals possess. The mod needs a utility item that allows you to set hats on your pets and farm animals

**Comment by iChun** [comment]
Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.

PS: We have a hat launcher now you can use to put hats on mobs (if supported)
