### ISSUE TITLE
Reassigning keybind not possible

### ISSUE THREAD

**Issue by Adonis0** [iChun/Hats#155]
This issue has been replicated by multiple people and multiple instances, and so I'm reporting it

It is not possible to change the keybind to open the GUI, whilst there is an option to do so, the reassigned key only persists in that instance of minecraft, closing and reopening minecraft will reset the keybind back to H. A variety of keys have been tested as recipients, with the same result.

**Comment by iChun** [comment]
Has anyone tried to change the key bind in the iChunUtil config GUI
instead?

**Comment by Adonis0** [comment]
Tested just then changing the keybinds within the iChunUtil options, while not intuitive to access, it was successful in changing the keybind across minecraft sessions.

**Comment by iChun** [comment]
https://github.com/iChun/Hats/commit/daa39f3a2f340c23aeb6941372aa049ac4ae3c72
