### ISSUE TITLE
[1.10.2] Hat Stand completely unusable

### ISSUE THREAD

**Issue by VermillionX** [iChun/Hats#158]
Simple enough, the newly released 1.10.2 version of Hat Stand does nothing and is infinite.
Upon crafting a hat stand, they can be placed infinitely, as if in creative mode; They occupy a full block; Cannot be attached to walls; Lack half the model (The middle wooden rod is missing); and most importantly, do nothing. Right clicking a hat stand does less than right clicking a block of cobblestone.
Yes, the Hats mod is also installed, and i've tried it with a fresh install with just forge and utility mods.

**Comment by iChun** [comment]
Huh, it was working in testing. Will look into when I can.

**Comment by iChun** [comment]
Is this still an issue with the 1.12.2 version of the mod?
