### ISSUE TITLE
1.12 version does not run in 1.12

### ISSUE THREAD

**Issue by NicMoore88** [iChun/Hats#159]
The 1.12+ version posted on Curse does not run in 1.12 as tagged.  It says it requires 1.12.2
[https://gyazo.com/66b8e8036891086244b28ae75e81a2c9](url)

I'm not sure if it is supposed to run in 1.12, but I hope so.

Thanks!

**Comment by iChun** [comment]
That's odd though. acceptedMinecraftVersions isn't set in the mod and the documentation for MC said that should be fine.... I don't know why this is happening. I'll have to look into when I get home.

**Comment by Zeevian** [comment]
same thing for 1.12.1

**Comment by iChun** [comment]
Fixed in version 7.0.1.
