### ISSUE TITLE
Support Player API

### ISSUE THREAD

**Issue by inklesspen1scripter** [iChun/Hats#162]
SmartMoving using Player API for animate player... and Hats can't find real position of Head.
Can you add support Player API for 1.7.10 etc?

**Comment by iChun** [comment]
MC... 1...7....10....?

**Comment by inklesspen1rus** [comment]
Yes
I can share more information with u later

**Comment by iChun** [comment]
Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.
