### ISSUE TITLE
[1.12.2] Compatibility With Mods

### ISSUE THREAD

**Issue by BuilderDan** [iChun/Hats#163]
Hello,

 

Your hats mod doesn’t appear to work / work well with these mods:

Deadly Creatures, Reptiles, mo’bends, Nether Ex, Animania

Whenever I played on 1.12 with those mods and your hat mod installed the image that pops up when you get a hat was purple and bugged, and hats only spawn on vanilla mobs, with Mo’Bends the hats float, with Animania the hats are displaced and don’t fit properly either… support for these mods would be greatly appreciated!

 

Thanks,
Dan

**Comment by iChun** [comment]
Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.
