### ISSUE TITLE
Cannot unassign keys for iChun mods

### ISSUE THREAD

**Issue by ghost** [iChun/Hats#164]
When selecting a keybind, I cannot remove the bind by pressing esc.

Is there no way to do this?

By the way, why don’t you just use the vanilla controls menu?

**Comment by iChun** [comment]
I added modifiers before Forge added them so it needed it's own GUI to be
set. No you can't unbind them but you can out them all on a key you don't
want to use. My keybinds also tell me when you release a key and Forge's
doesn't.

**Comment by iChun** [comment]
Hats also uses an old method to set a keybind so it'd be better to set them
in the config GUI rather than the ingame one.

**Comment by iChun** [comment]
Will be addressed in iChunUtil for 1.14.
