### ISSUE TITLE
[1.12.2] Cannot craft hat stand

### ISSUE THREAD

**Issue by ghost** [iChun/Hats#165]
There’s no crafting recipe for the hat stand. I cannot craft it using an oak wood slab and a stick, nor can I view the recipe in [JEI](https://minecraft.curseforge.com/projects/just-enough-items-jei).

****

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2531
**Hat Stand version**: 7.0.1
**Hats version**: 7.0.2
**iChunUtil version**: 7.1.2

**Comment by PapiDimmi** [comment]
By the way, FYI, Forge’s “mod options” menu says that I’m using version 7.0.0 of Hat Stand, even though I’m using version 7.0.1.

**Comment by iChun** [comment]
Should be fixed for Hat Stand 7.1.0. Sorry for the long wait!
