### ISSUE TITLE
[1.10.2] Crash when placing or interacting with hatstand

### ISSUE THREAD

**Issue by beanaboston** [iChun/Hats#167]
I installed this mod and upon placing the hatstand it crashes the game. (https://pastebin.com/xMweKctn)
I can go back into the world safely, and the hatstand is there but when I right click it it crashes as well. (https://pastebin.com/i9ns3a8A) I also tested this on an install with just Hat Stand and it's required mods, same crashes happened.

**Comment by FumoKisser69** [comment]
But what was the solution????
