### ISSUE TITLE
[1.12.2] No recipe for Hat Stand

### ISSUE THREAD

**Issue by garrim** [iChun/Hats#169]
HI.

When clicking on the Hat Stand in JEI I get no recipe for it.
When I try to craft it (slab, stick) nothing happens.
In creative I can give me a stand that works fine.

Here is my **[Pastebin](https://pastebin.com/AyKAtAUq)**.

Kind regards
Garrim

**Comment by invalidtask** [comment]
I'm experiencing the same issue. I also tried the stick and slab recipe available on the wiki. Doesn't work. Have to /give to get the hat stand which is not that fun.

**Comment by iChun** [comment]
Should be fixed for Hat Stand 7.1.0. Sorry for the long wait!
