### ISSUE TITLE
FTB PermissionHandler incompatibility

### ISSUE THREAD

**Issue by tyggna** [iChun/Hats#173]
Again, super low priority because everything still works, but this is likely causing some hiccups with your mod and FTB Utilities.  In this case, it prevents your mod from forming an HTTP connection.  Pertinent tracebacks below.

> 
> [17:09:09] [Server thread/WARN] [FML]: Replacing net.minecraftforge.server.permission.DefaultPermissionHandler with com.feed_the_beast.ftbutilities.ranks.FTBUtilitiesPermissionHandler [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.ExceptionInInitializerError
>  in most cases indicates a broken mod.
> 

> [17:09:09] [Server thread/WARN] [FML]: Replacing net.minecraftforge.server.permission.DefaultPermissionHandler with com.feed_the_beast.ftbutilities.ranks.FTBUtilitiesPermissionHandler [Hats Download/Read Hats Thread/INFO] [STDERR]: [me.ichun.mods.hats.common.thread.ThreadHatsReader:run:85]:  at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
> [17:09:10] [Hats Download/Read Hats Thread/INFO] [STDERR]: [me.ichun.mods.hats.common.thread.ThreadHatsReader:run:85]:  at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:848)
> [17:09:10] [Hats Download/Read Hats Thread/INFO] [STDERR]: [me.ichun.mods.hats.common.thread.ThreadHatsReader:run:85]:  at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
> [17:09:10] [Hats Download/Read Hats Thread/INFO] [STDERR]: [me.ichun.mods.hats.common.thread.ThreadHatsReader:run:85]:  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
> [17:09:10] [Hats Download/Read Hats Thread/INFO] [STDERR]: [me.ichun.mods.hats.common.thread.ThreadHatsReader:run:85]:  at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
> [17:09:10] [Hats Download/Read Hats Thread/INFO] [STDERR]: [me.ichun.mods.hats.common.thread.ThreadHatsReader:run:85]:  at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
> [17:09:10] [Hats Download/Read Hats Thread/INFO] [STDERR]: [me.ichun.mods.hats.common.thread.ThreadHatsReader:run:85]:  at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
> [17:09:10] [Hats Download/Read Hats Thread/INFO] [STDERR]: [me.ichun.mods.hats.common.thread.ThreadHatsReader:run:85]:  at java.security.AccessController.doPrivileged(Native Method)
> [17:09:10] [Hats Download/Read Hats Thread/INFO] [STDERR]: [me.ichun.mods.hats.common.thread.ThreadHatsReader:run:85]:  at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
> [17:09:10] [Hats Download/Read Hats Thread/INFO] [STDERR]: [me.ichun.mods.hats.common.thread.ThreadHatsReader:run:85]:  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
> [17:09:10] [Hats Download/Read Hats Thread/INFO] [STDERR]: [me.ichun.mods.hats.common.thread.ThreadHatsReader:run:85]:  at me.ichun.mods.hats.common.thread.ThreadHatsReader.run(ThreadHatsReader.java:51)
>

**Comment by iChun** [comment]
Creeperhost moved domains and added a redirect header. I think this should be fixed in 7.1.0.
