### ISSUE TITLE
Not able to trade!

### ISSUE THREAD

**Issue by HFinner** [iChun/Hats#174]
Using hats on 1.12.2 v7.0.2, not able to ready up with trade partner. We both tossed a hat into the trade and when we tried to hit ready to trade nothing was happening, we were even both clicking on it at the same time and nada.

**Comment by thewismit** [comment]
Using the same version of the mod with the FoolCraft3 modpack and am also unable to trade.

**Comment by RobertLSnead** [comment]
Ditto but with StoneBlock mod pack!

**Comment by iChun** [comment]
Sorry for leaving this broken for so long! It's been fixed for v7.1.0
