### ISSUE TITLE
Crash when viewing player in thaumcraft morph

### ISSUE THREAD

**Issue by Zelda-Swordsman** [iChun/Hats#175]
When combined with the morph mod, morphing into certain thaumcraft mobs causes a crash when in F5 mode, and when looking at other morphed players. Mods being used are in the Foolcraft 3 modpack Release- 1.4.5 with VanillaFix and LagGoggles added. Acording to VanillaFix, this mod is the culprit.
Crash Log
https://paste.dimdev.org/opotozowig.mccrash

**Comment by Zelda-Swordsman** [comment]
Refers to the issue of displaying hats on thaumcraft mobs #172

**Comment by iChun** [comment]
This was a different crash, Will be fixed in 7.1.0.
