### ISSUE TITLE
Basic hat pack don't install on first run 

### ISSUE THREAD

**Issue by Rnafout** [iChun/Hats#176]
Hello, 
First thanks for your amazing mod, it's really funny. 

I've installed it but on the first run of the game (successfull) no mobs had hats (obviously i'm talking about new generated mobs). 
I've tried installing other hats from a custom pack on the internet and they work just fine. I'm just missing the initial hats pack wich should be "install on the first run".

I tryied changing to other version of the mod for the same minecraft version (1.12.2) and it don't work either. 

Can you help me solve this or give a zipped file with the .tcn files ? 
Thanks you !

**Comment by iChun** [comment]
What version of the mod are you using?

**Comment by Rnafout** [comment]
(In the mean time i've extracted and downloaded mannually using the link you use in the code, as i'm a developper myself and i understand java. Placing mannually every file in the "hat" folder make it work but it's not viable solution in case of other also encounter it) 

My version is Hats 7.0.2 for 1.12.2 MC

**Comment by SkunkWorks150** [comment]
Hello,
I am having a similar but not identical problem. My problem, which I have never experienced before except recently on 1.7.10 and 1.12.2, is that when first initializing, Hats isn't downloading nearly any of all the hats that are supposed to be in the mod. I'll attach screenshots of all the hats I used to have and all the ones it's downloading. I sort of fixed it when in 1.7.10 as I just copy pasted from an old 1.7.10 instance that had all of them, but with 1.12 it looks like a different file extension (.tbl) is used so i don't think that solution will work. If there is at least somewhere i can access all the hat files that i haven't found yet that would be a temporary solution.

I'm using 7.0.2 in the FTB Continuum Pack, and my 1.7.10 problem was in FTB Infinity Evolved.
Any help is appreciated, thank you.

![old 1 7 10 files goes all the way to z](https://user-images.githubusercontent.com/35987052/46909900-2a7ada00-ceef-11e8-84c2-8acc59872c30.PNG)

![what hat s is dowloading](https://user-images.githubusercontent.com/35987052/46909901-2f3f8e00-ceef-11e8-833f-4b19993bcb23.PNG)

**Comment by Gideon9212** [comment]
From what I'm seeing, any FTB modpack in the 1.7.10 version won't download past Abraham's hat and just make that the only hat in the folder.
Is there a direct link or backup to all the hats?

**Comment by bobbygoin** [comment]
Can you please provide the hat pack files? I'm missing them entirely.

**Comment by iChun** [comment]
Please use the temp solution listed here:

https://github.com/iChun/Hats/issues/189#issuecomment-533869057

I'll sort it out when I can.
