### ISSUE TITLE
not working help 

### ISSUE THREAD

**Issue by ShadowImmortal** [iChun/Hats#177]
so when i download it for 1.12.2 it says ichunutil requires 7.0.2 or above and below 8.0.0 missing and i downloaded 7.0.2 but it still says that :/ help please i begg you or you can try to make the 1.12.2 7.0.3? cuz i dont want to do it in 1.12 or other versions cuz all my mods are 1.12.2 and am trying to make i survival mod world like crazy craft i have like 7 mods installed and i want this mod cuz it help me go more in the open cuz i always mine xD so can you help?

**Comment by ShadowImmortal** [comment]
and also creator if you cant help me than just reply other wise i dont know if you can help

**Comment by iChun** [comment]
I hoped you've figured it out by now! If not, make a new issue!
