### ISSUE TITLE
Mobs don't drop hats.

### ISSUE THREAD

**Issue by TheDaneSimon** [iChun/Hats#180]
Mobs don't drop hats, and we have no hats while in menu, even though each of us has a hat on.
and i can not se my own hat, but my friend can see the hat, and again cant see them in my hats menu.
it does work in single player mode, but not on the dedicated server.

**Comment by iChun** [comment]
Did you remember to install Hats on the server? Is it working serverside?
Your situation makes me think the client side isn't being told the server
has the mod.

**Comment by TheDaneSimon** [comment]
this is really weird. originally i started the server with the mod and it created the folder and the server didn't say anything bad about the mod, so i assumed the mod it self was bugged, i restarted the server the same day before the original post, but left it over night as it still wasn't working, but when i restarted again today to try to see every warning the server would post, there was nothing to note and the mod apparently started working as expected.
so a temporary bug that a can't recreate but thanks for the fast response 💯
