### ISSUE TITLE
Losing hats when rejoining my server.

### ISSUE THREAD

**Issue by Sintokii** [iChun/Hats#181]
I have a server with the hats mod installed, and everything seemed to be working fine. That is, until my friends and I got off for the day. When we got back on, all the hats we've collected have vanished. I have a couple hat packs installed in the server files, because there weren't any hats showing up on mobs besides the Abe Lincoln one. Do you need to install the hat packs on your client as well? Using 1.7.10 btw.

**Comment by iChun** [comment]
Sorry but I have long stopped support for MC 1.7.10. 

I also realise that my comment is 5 months too late.
