### ISSUE TITLE
[1.12.2] Crash when Morphing into FireFly

### ISSUE THREAD

**Issue by ApexModder** [iChun/Hats#186]
Was playing on a modded server when, one of the players killed and morphed into the Firefly mob from TwilightForest and wearing a hat. Tested and recreated only happens to Firefly or mobs that dont have a had.

Player cant rejoin the server after crash, as when they join they crash again with same issue, no time to change their morph to stop crashing.

Crashlog: https://paste.dimdev.org/gafocakoci.mccrash

**Comment by iChun** [comment]
Should be fixed in 7.1.0. Thanks for the report!
