### ISSUE TITLE
No hats appearing

### ISSUE THREAD

**Issue by GoshUG** [iChun/Hats#188]
I have played with the mod in the past and know that in Creative I should have access to all hats and in Survival - I should be able to find mobs with hats... Neither of those are working properly... I have no access to hats whatsoever... I have no hats available hats in Creative and no mobs spawn with hats in Survival.

**Comment by NEVIP** [comment]
I have exactly the same problem.

**Comment by bobbygoin** [comment]
Yeah the hats folder is empty aside from "Favorites" but that is empty too.

**Comment by mild-prowler** [comment]
You can find my solution to this issue here: #189

**Comment by GoshUG** [comment]
YO, THANKS!

**Comment by iChun** [comment]
https://github.com/iChun/Hats/issues/189#issuecomment-537206790
