### ISSUE TITLE
Please set update URL

### ISSUE THREAD

**Issue by miiichael** [iChun/Hats#190]
I probably would have noticed the release to fix #189 sooner, had Minecraft told me there was a new version available. :stuck_out_tongue:

**Comment by iChun** [comment]
I used to have an update JSON but knowing me I'd probably just forget to update it 😂

Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.

**Comment by miiichael** [comment]
Ah, but does the new version set an updateJSONURL? 😅

**Comment by iChun** [comment]
It still does not. I will forget to update it so I chose not to have one. 😂

If curseforge auto generates one when I load a new file then I'll probably
add one, don't know if they do
