### ISSUE TITLE
Hats are not appearing in Multiplayer

### ISSUE THREAD

**Issue by felipeleite5w** [iChun/Hats#191]
Hats are not appearing in Multiplayer

My modpack: https://www.technicpack.net/modpack/colisaodotempo.933144

**Comment by iChun** [comment]
Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.
