### ISSUE TITLE
Working on Single player- Not multiplayer- Server is updated

### ISSUE THREAD

**Issue by Iamburgie** [iChun/Hats#192]
Hello! 

I have tried all the fixes from the other issues. 
However I am still not getting there. It works perfectly in single player. it also works in multiplayer 

However : It does not spawn on animals, I can open the menu AND in creative mode I can see the hats names. But that is about it

they just dont show- nor spawn. When in creative mode I click on a hat, it does not load nor spawn. I tried reinstalling with the previous fix ( the 1.12 fix) but it keeps giving me the same thing.

How would I need to proceed from here ?

**Comment by iChun** [comment]
Are you sure it's installed on the server and the server has all the hats?

**Comment by Iamburgie** [comment]
Yeah I am sure- I now got a hat, however it did not spawn on the animals or enemy's. It just happend at random. So its mainly just not showing up in general

**Comment by iChun** [comment]
Does the server have all the hats. I need to check the server's log file

**Comment by Iamburgie** [comment]
Hey! It took a while, but it seems to be working now. I dont know what changed, but I think it was just not loading properly and eventually it did ! 
So I think its mainly because of loading issues.
