### ISSUE TITLE
(Optifine INCOMPATIBILITY) Hats are green with shaders on.

### ISSUE THREAD

**Issue by FinalKill9175** [iChun/Hats#193]
Title says it all. I am playing with forge and optifine on minecraft 1.12.2. All hats are green and only hues of green when shaders are enabled.
![2020-02-20_12 15 19](https://user-images.githubusercontent.com/7538329/74965560-15636480-53db-11ea-82fc-955ccdb0bc46.png)

**Comment by iChun** [comment]
Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.
