### ISSUE TITLE
the hat does not appear on the mob despite it sends me a message that they are here

### ISSUE THREAD

**Issue by Gaspour6** [iChun/Hats#194]
i had install hats on my mc and of course i had install inchun too but that's don't work i had a message tell's me the hats are on mob and i should to kill it for hats but they aren't there 

i have forge on 1.12.2 and i have that mod whit it :
securitycraft,secretroom,morph,inchun,CustomNPCs,worldedit. 
I hope you will answer .

**Comment by Gaspour6** [comment]
i play on singleplayer

**Comment by Gaspour6** [comment]
i tried to reinstalled the version 7.1.0 but that dont work

**Comment by Gameknight6916** [comment]
Well... the way you get hats has kinda sorta died and you can't get them. Some mods have already ported their own hats into the game using this mod but that's about it.

**Comment by pinheadtf2** [comment]
I can post my hats on a temporary download and you can put them in your mods folder. Give me a ping!

**Comment by Jmunoz1789** [comment]
Can I also get the models they do not spawn in my crazy craft 4 server.

**Comment by iChun** [comment]
Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.
