### ISSUE TITLE
Huge amount of Exceptions thrown.

### ISSUE THREAD

**Issue by Flosus** [iChun/Hats#195]
Hello,

Im playing with the MC Eternal Modpack. After noticing some lag spikes I started up Mission control and saw a lot of Exceptions thrown by the Hats mod:
![2020-04-26 13_34_05-Greenshot](https://user-images.githubusercontent.com/4223452/80306282-a03d5280-87c2-11ea-998b-fb4a7b8214b0.png)

The Version is 1.12.2-7.1.0

I hope this will help you.

**Comment by iChun** [comment]
Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.
