### ISSUE TITLE
I can't disable Contributors Hats!

### ISSUE THREAD

**Issue by SkyAdri-mc** [iChun/Hats#198]
I need an ability to disable the auto downloading of hats when i start the game, because i want to delete the Contributors Hats because they look very Ugly, but im not able to!

**Comment by iChun** [comment]
Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.

Hats now extracts the hats locally when it detects the extracted marker isn't there, so you can delete off hats you don't want after that now. I guess to a degree it's been addressed!
