### ISSUE TITLE
Hat rarity?

### ISSUE THREAD

**Issue by josephyooo** [iChun/Hats#199]
I see no rankings or documentation on the different rarity colors. Of the 6 (green, white, dark blue, yellow, orange, pink, light blue), I can only guess that the first 4 are more common than the last 3, but not in which order. Any sort of documentation of this, such as on the wiki or curseforge page, or even as one of the "Protips" would be quite useful. 

If this already exists, and I've missed it, please link me where I can find these rarity names.

**Comment by iChun** [comment]
I'll remember to add a protip in somewhere in the future versions of Hats, but for your reference, it's here in this function (I actually had to go look it up myself as well, heh) https://github.com/iChun/Hats/blob/4f4946343770d68355aab17c29a56b1008d4d6fc/src/main/java/me/ichun/mods/hats/common/core/HatHandler.java#L581

Aqua being the rarest and as it goes down it's more common.

**Comment by iChun** [comment]
Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.

Also FWIW I've added the rarity name to the tooltip for the 1.16.5+ versions. Thanks for this!
