### ISSUE TITLE
Hats doesn't appears anymore

### ISSUE THREAD

**Issue by Gaspour0** [iChun/Hats#200]
Recently , i've try to play minecraft with hats mod in 1.12.2 so i try it in solo for see if that's work well and if i didn't mistake somewhere. But the hats won't appears at all not in mobs and not on me of course i have Ichuntil 7.2.1 and hats 7.0.1 in 1.12.2 and i didn't have any other mods whit him.
When i open the world it say that's Hats in on the game and we should kill mob for have hats and the hat's menu work pretty well but there is no hat.
Thanks for help in advance if you can

**Comment by iChun** [comment]
Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.
