### ISSUE TITLE
ive been playing for hours and havent found a mob with a hat

### ISSUE THREAD

**Issue by dylkiller123** [iChun/Hats#202]

**Comment by dylkiller123** [comment]
why cant i find any after playing for a really long time

**Comment by iChun** [comment]
Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.
