### ISSUE TITLE
My...my humvee has a hat

### ISSUE THREAD

**Issue by ghost** [iChun/Hats#203]
Yes, thats right

My High Mobility Multipurpose Wheeled Vehicle from ATOM_14_A's MCHeli expansion pack has found itself a new racoon hat

![image](https://user-images.githubusercontent.com/64351383/108125069-f04d1480-7075-11eb-915f-a1562373c0da.png)
![image](https://user-images.githubusercontent.com/64351383/108125086-f7742280-7075-11eb-9cfe-afec421a1bc1.png)

Its really funny but when you get in that seat it obstructs pretty much all of your forward vision, so is there a way to disable hats for certain mobs that...aren't mobs?

**Comment by ghost** [comment]
Update: its in all mcheli ground vehicles 
As soon as you start driving the hat glitches out and stays where you spawned in said vehicle
![image](https://user-images.githubusercontent.com/64351383/108125927-2a6ae600-7077-11eb-84fa-ff004d0feb72.png)
![image](https://user-images.githubusercontent.com/64351383/108125939-2f2f9a00-7077-11eb-8907-2e50339d9467.png)

**Comment by iChun** [comment]
Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.

This issue might still be an issue I think but there's a way to disable this via JSON files which is what Hats uses for mob support now.

NGL This was a funny one, got a laugh out of me, so kudos for that!
