### ISSUE TITLE
Hat GUI not working in crazy craft 4.0

### ISSUE THREAD

**Issue by CouchMilklmao** [iChun/Hats#204]
When i press H, the hat gui doesnt come up. i can unlock hats and mobs spawn with them, but i cant seem to open the gui itself. i have no keybind set as H. so i have no clue why this might be happening.

**Comment by iChun** [comment]
It might have been rebound by the pack? Gotta check your configs. IIRC there's also a way to disable the UI on the server config. Might wanna check that.

Closing all issues as Hats has been rewritten from the ground up and the old mod for a long time now was no longer supported.. I'm sorry I wasn't able to address your issue. If you're still playing modded Minecraft, consider checking out Hats for 1.16.5+.
