### ISSUE TITLE
How to prevent this message on server login, when hats is on both client and server

### ISSUE THREAD

**Issue by ModernGamingWorld** [iChun/Hats#205]
![2021-04-11_13 20 53](https://user-images.githubusercontent.com/75923060/114316358-ce499e80-9ac8-11eb-931b-c653f4aee224.png)

Latest 1.16.5

**Comment by iChun** [comment]
How long does it take for you to log into the world?

**Comment by GrumpyPirate** [comment]
Having the same issue here. We've added the latest Hats ver to a modded Valhelsia 3 server, and it takes us around 1min~ to fully load into the world after hitting the Login button. I imagine larger modpacks (e.g. ATM) would have an even longer loading time. Perhaps this is something that could be configurable, or even disabled?

**Comment by iChun** [comment]
I've pushed out a new build, 10.1.0. Could you guys try it out and report
back?

**Comment by GrumpyPirate** [comment]
Will take a look as soon as possible!

**Comment by GrumpyPirate** [comment]
Can confirm 10.1.0 resolves the issue, we no longer get the message on login. And more importantly, hats continue to work on the server. Thanks for resolving!
