### ISSUE TITLE
Crash on MC 1.16.5

### ISSUE THREAD

**Issue by Fehrstix** [iChun/Hats#206]
Hello. 
I have a problem when launching Minecraft. Could you, please, help me to fix it?
[crash-2021-04-12_15.07.08-fml.txt](https://github.com/iChun/Hats/files/6296552/crash-2021-04-12_15.07.08-fml.txt)

**Comment by iChun** [comment]
You need to use the iChunUtil 10.1.0 or later. I'm surprised FML didn't catch this when loading the mods.toml files
