### ISSUE TITLE
10.1.0 TNT Crash

### ISSUE THREAD

**Issue by MyNamesRaph** [iChun/Hats#217]
It seems the mod tried to add a hat to primed TNT and crashed the server.

Crash report : https://pastebin.com/u6qt0AbP

**Comment by iChun** [comment]
I can't quite replicate this on my end, I suspect there might be another mod removing the entity the TNT blew up before Hats can get to it, thus removing the Hat capability and causing the crash. I've added a check for this now in the next version and hopefully the crash stops.
