### ISSUE TITLE
Hat is shown over the helmet

### ISSUE THREAD

**Issue by jahirtrap** [iChun/Hats#218]
- Minecraft version: 1.16.5 

Add an option to disable hats from showing over the helmet, as some look too big:
Without helmet 👍:
![2021-05-08_22 40 17](https://user-images.githubusercontent.com/75038202/117559859-8463c200-b04e-11eb-9957-518026ddc26e.png)
![2021-05-08_22 42 28](https://user-images.githubusercontent.com/75038202/117559888-b7a65100-b04e-11eb-8d51-e70e86e5bc95.png)

With helmet 👎:
![2021-05-08_22 40 34](https://user-images.githubusercontent.com/75038202/117559874-9d6c7300-b04e-11eb-9ee5-e2d936484eb6.png)
![2021-05-08_22 42 33_2](https://user-images.githubusercontent.com/75038202/117559889-bbd26e80-b04e-11eb-803c-9ee8d853e59b.png)

**Comment by iChun** [comment]
Have you considered maybe just removing the hat?

**Comment by jahirtrap** [comment]
I want to use the hat but the armor (helmet) makes the hat increase in size, this doesn't happen in version 1.12.2

**Comment by iChun** [comment]
If you want, you can edit the JSON files that iChunUtil uses to define the armor scales. Remove the line `  "headArmorScale": 1.265625
` from the file. Be careful not the break the JSON formatting.

**Comment by iChun** [comment]
You can find these files in /config/ichunutil/heads/
