### ISSUE TITLE
[1.16.5] Player is kicked from the server upon recieving OP status

### ISSUE THREAD

**Issue by Speeder323** [iChun/Hats#219]
If the player gets OP on the server, they are kicked from it.
Attempting to join back results in the same error instantly kicking them out again.
The issue instantly goes away upon revoking OP status.
![obraz](https://user-images.githubusercontent.com/61844671/118086567-77cfc880-b3c4-11eb-9458-9ed667b43a5f.png)
[from_server_log.txt](https://github.com/iChun/Hats/files/6470664/from_server_log.txt)
There doesn't seem to be anything relevant in the client log file.

**Comment by iChun** [comment]
Should be fixed in the next version of Hats. Thanks for the report.
