### ISSUE TITLE
[1.16.5] Conflict with Improved Genetics Mod

### ISSUE THREAD

**Issue by rjlawrence** [iChun/Hats#222]
There appears to be a conflict with the Improved Genetics Mod. Pushing H crashes and throws an error that starts with the improved genetics. I don't know if it's on this mods end or Improved Genetics.
[crash-2021-05-25_22.24.01-client.txt](https://github.com/iChun/Hats/files/6543492/crash-2021-05-25_22.24.01-client.txt)

**Comment by iChun** [comment]
This log should be sent to them. I think they're expecting a player from
the render perspective, which is not always the case. You can work around
this by forcing the GUI fallback in the hats config
