### ISSUE TITLE
Advent of Ascension support.

### ISSUE THREAD

**Issue by ghost** [iChun/Hats#223]

**Comment by iChun** [comment]
This is an issue, how...? 🤔

**Comment by ghost** [comment]
Hats doesn't appear on AoA mobs.

**Comment by iChun** [comment]
And mod-mob support is a community effort using a combination of Tabula and iChunUtil to export/generate HeadInfo JSON files. 

If you would like to help, feel free to join the Discord or submit JSON files to add support for those mobs rather than submitting an issue with no description.

**Comment by ghost** [comment]
Ok, Thanks. I try to play with JSON headinfo.
