### ISSUE TITLE
Killing with Sacrificial dagger/knife doesn't give hats

### ISSUE THREAD

**Issue by Chewypuppielover** [iChun/Hats#232]
Killing Mobs with Blood Magic's Sacrificial dagger/knife doesn't give hats in 1.16 at least. I'm guessing it has to do with the type of damage it uses and so there might not be a fix.

**Comment by iChun** [comment]
I had a look at their source and Wot is setting the entity health to a
negative value and calling the onDeath method.
https://github.com/WayofTime/BloodMagic/blob/1.16.3/src/main/java/wayoftime/bloodmagic/common/item/ItemDaggerOfSacrifice.java#L67

Hats relies on Forge's death event trigger which ends up being bypassed by
the sacrificial dagger, so Hats doesn't even know an entity just died.

This issue might have to be addressed on their end to fire a
LivingDeathEvent when the dagger is used.

**Comment by iChun** [comment]
Spoke to WoT about this, they should fix this on their end
