### ISSUE TITLE
Crash on pressing h

### ISSUE THREAD

**Issue by jjrizo1101** [iChun/Hats#246]
Hello, I'm having an issue that whenever I press "H" or whatever other key I bind to the Hat menu, it instantly crashes minecraft.
I saw an issue that is similar to mine but I'm submitting mine so see if its different. Please help
[crash-2022-03-11_13.19.43-client.txt](https://github.com/iChun/Hats/files/8234414/crash-2022-03-11_13.19.43-client.txt)

**Comment by iChun** [comment]
For my reference:
https://github.com/henkelmax/ultimate-plane-mod/blob/master/src/main/java/de/maxhenkel/plane/events/CapabilityEvents.java#L22

**Comment by iChun** [comment]
Should be fixed for the next update
