### ISSUE TITLE
1.16.5 forge latest version crash on startup

### ISSUE THREAD

**Issue by Jetpack-Cat** [iChun/Hats#248]
At times crashes on game startup
[crash-2022-04-26_16.36.49-fml.txt](https://github.com/iChun/Hats/files/8567521/crash-2022-04-26_16.36.49-fml.txt)

**Comment by iChun** [comment]
That's a crash happening in Forge's side. I'm not too sure what's up, asking on their Discord for support. May be a Forge issue that will be fixed on their side.

**Comment by iChun** [comment]
According to sciwhiz12, one of the Triage members of Forge, they suggest you switch to OpenJDK instead of OpenJ9 for your Java Runtime. Could you try that out?
