### ISSUE TITLE
[1.10.2] Empty Hats Folder

### ISSUE THREAD

**Issue by Reyshyram** [iChun/Hats#253]
Can anyone provide me the hats folder for the 1.10.2 version, please ?

**Comment by TurboTechWizard** [comment]
I have the hat folder for 1.7.10. I am not sure if it will work but you could try. [Download](https://github.com/iChun/Hats/files/3640354/hats-1.7.10-2.zip)

**Comment by Reyshyram** [comment]
> I have the hat folder for 1.7.10. I am not sure if it will work but you could try. [Download](https://github.com/iChun/Hats/files/3640354/hats-1.7.10-2.zip)

Thank you, I already tried the 1.12.2 folder and it functioned !
