### ISSUE TITLE
[1.7.10] The hats themselves don't seem to be installing with the mod!

### ISSUE THREAD

**Issue by Duscara** [iChun/Hats#258]
I've tried doing it in .minecraft instead of a CurseForge modpack, changing the hat mode, and more, but it seems that the installation didn't give me any hats. Can someone please send me a link to all the hats that should come with the mod so I can place them in the /hats folder. That is where they're supposed to be, right?

**Comment by iChun** [comment]
https://github.com/iChun/Hats/issues/189#issuecomment-533404736
