### ISSUE TITLE
1.7.10 hats mod isnt working, (given method tried and doesnt work)

### ISSUE THREAD

**Issue by ooooooooooooohhhhh** [iChun/Hats#259]
playing on 1.7.10 and the hats dont appear on mobs, when I do the guide and extract all the hats into the hat folder it just gives me all the hats in the game, am I putting it in the wrong place or did i miss a step? because when I extract it into the hat folder it gives me every hat in the game and none of the mobs spawn with them please help.

**Comment by iChun** [comment]
make sure the server has the mod installed and you're not playing in creative mode. 1.7.10 support ended years ago
